object SplashScreen: TSplashScreen
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'SplashScreen'
  ClientHeight = 100
  ClientWidth = 300
  Color = -1
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Visible = True
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 0
    Top = 40
    Width = 300
    Height = 17
    Alignment = taCenter
    AutoSize = False
    Caption = 'Carregando..'
    Font.Charset = ANSI_CHARSET
    Font.Color = clGray
    Font.Height = -13
    Font.Name = 'Roboto'
    Font.Style = [fsItalic]
    ParentFont = False
  end
end
